name: code_bangladesh_mobile_app
description: CodeBangladesh.org Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  logger:
  url_launcher: ^6.0.3
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0
  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/img/tortoise.png"
